version: '3.8'

services:
    db:
      container_name: vank-db-${NODE_ENV}
      image: postgres:14
      ports: 
        - ${DB_PORT}:5432
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}